services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - myapp_network
    environment:
      - DJANGO_SETTINGS_MODULE=yourproject.settings

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - myapp_network
    command: --default-authentication-plugin=mysql_native_password

  # Optional: Add pgAdmin or Adminer for database management
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - myapp_network

volumes:
  mysql_data:

networks:
  myapp_network: